### ISSUE TITLE
Codesign identity is not set properly

### ISSUE THREAD

**Issue by silvansky** [thelvis4/XCProvisioner#2]
After calling `xcprovisioner` via command

`xcprovisioner --project MyApp.xcodeproj --target MyApp --configuration Release --identity "iPhone Distribution: MyCompany (TEAM-ID)" --team TEAM-ID --specifier "ProfileName"`

Build fails. The reason is that identity is set for configuration "Release" but not for "Release / Any iOS SDK". See screenshot below:

![_2017-03-02_14_25_01](https://cloud.githubusercontent.com/assets/900074/23505608/d0fcb028-ff5d-11e6-93a3-724de1230462.png)

**Comment by silvansky** [comment]
Created PR with a quick fix: https://github.com/thelvis4/XCProvisioner/pull/3

**Comment by thelvis4** [comment]
Thank you, @silvansky! 🙌 

I have definitely forgotten about SDK specifiers. 😬 
I opened a PR that fixes this issue and other potential issues regarding SDK specifiers.
Thanks again for your valuable finding!

**Comment by thelvis4** [comment]
I've released a new public version (`0.1.3`) that includes the fix for this issue. 🚀
